package com.batterycast.quant.forecasting.explain

import com.batterycast.quant.forecasting.ForecastContext
import com.batterycast.quant.forecasting.model.DataMaturity
import com.batterycast.quant.forecasting.model.DriverDirection
import com.batterycast.quant.forecasting.model.ForecastDriver
import com.batterycast.quant.forecasting.model.ThermalBucket
import com.batterycast.quant.forecasting.stats.RobustStats
import com.batterycast.quant.telemetry.model.FieldSupport
import kotlin.math.abs
import kotlin.math.roundToInt

/**
 * Explains why the forecast looks the way it does.
 *
 * Every statement here is generated by comparing two real quantities, and each carries the number
 * that produced it. There are no stock explanations: if nothing measurable has changed, the
 * explainer says so rather than inventing a narrative.
 *
 * It also deliberately never attributes drain to a named application. Android does not give an
 * app-level energy figure a third-party app can defend, so the strongest claim made here is that
 * a kind of activity *coincided* with a change in drain.
 */
class ChangeExplainer {

    fun explain(context: ForecastContext): List<ForecastDriver> {
        val drivers = mutableListOf<ForecastDriver>()

        drivers += drainVersusBaseline(context)
        drivers += temperatureTrend(context)
        drivers += powerSaveChange(context)
        drivers += screenTimeComparison(context)
        drivers += usageCoincidence(context)
        drivers += uncertaintyNotes(context)

        if (drivers.isEmpty()) {
            drivers += ForecastDriver(
                headline = "Nothing unusual in the last hour",
                detail = "Battery behaviour is close to what this phone normally does in this state.",
                direction = DriverDirection.NEUTRAL,
                magnitude = null,
            )
        }

        return drivers
    }

    /**
     * The headline driver: how the last hour compares with the learned baseline for this state.
     */
    private fun drainVersusBaseline(context: ForecastContext): List<ForecastDriver> {
        val recent = context.estimates.blendedPercentPerHour ?: return emptyList()
        val baseline = context.snapshot.drainByRegime[context.currentRegime]?.mean ?: return emptyList()
        if (baseline <= MIN_BASELINE) return emptyList()
        if (context.maturity < DataMaturity.BASIC) return emptyList()

        val ratio = recent.ratePerHour / baseline
        val percentDifference = ((ratio - 1.0) * 100).roundToInt()
        if (abs(percentDifference) < MIN_REPORTABLE_DIFFERENCE) return emptyList()

        val stateDescription = context.currentRegime.displayName.lowercase()
        return listOf(
            if (percentDifference > 0) {
                ForecastDriver(
                    headline = "Draining about $percentDifference% faster than usual",
                    detail = "Over the last hour the battery lost ${format(recent.ratePerHour)}%/h, " +
                        "against ${format(baseline)}%/h typical for $stateDescription on this phone.",
                    direction = DriverDirection.WORSE,
                    magnitude = ratio,
                )
            } else {
                ForecastDriver(
                    headline = "Draining about ${abs(percentDifference)}% more slowly than usual",
                    detail = "Over the last hour the battery lost ${format(recent.ratePerHour)}%/h, " +
                        "against ${format(baseline)}%/h typical for $stateDescription on this phone.",
                    direction = DriverDirection.BETTER,
                    magnitude = ratio,
                )
            },
        )
    }

    private fun temperatureTrend(context: ForecastContext): List<ForecastDriver> {
        val observations = context.cleaned.observations
        if (observations.size < 6) return emptyList()

        val cutoff = context.nowMs - RECENT_WINDOW_MS
        val recent = observations.filter { it.timestampMs >= cutoff }.mapNotNull { it.temperatureCelsius }
        val earlier = observations.filter { it.timestampMs < cutoff }.mapNotNull { it.temperatureCelsius }
        if (recent.size < 3 || earlier.size < 3) return emptyList()

        val recentMedian = RobustStats.median(recent) ?: return emptyList()
        val earlierMedian = RobustStats.median(earlier) ?: return emptyList()
        val delta = recentMedian - earlierMedian
        if (abs(delta) < MIN_TEMPERATURE_DELTA_C) return emptyList()

        return listOf(
            if (delta > 0) {
                ForecastDriver(
                    headline = "Battery temperature rose ${format(delta)} °C",
                    detail = "Now around ${format(recentMedian)} °C. Warmer batteries discharge less " +
                        "predictably, so the forecast interval has widened.",
                    direction = DriverDirection.UNCERTAINTY,
                    magnitude = delta,
                )
            } else {
                ForecastDriver(
                    headline = "Battery temperature fell ${format(abs(delta))} °C",
                    detail = "Now around ${format(recentMedian)} °C, which usually means the phone " +
                        "is working less hard than it was.",
                    direction = DriverDirection.BETTER,
                    magnitude = delta,
                )
            },
        )
    }

    private fun powerSaveChange(context: ForecastContext): List<ForecastDriver> {
        val observations = context.cleaned.observations
        if (observations.size < 3) return emptyList()

        val latest = observations.last()
        val previousState = observations.dropLast(1).lastOrNull { it.powerSaveEnabled != latest.powerSaveEnabled }
            ?: return emptyList()
        if (context.nowMs - previousState.timestampMs > POWER_SAVE_WINDOW_MS) return emptyList()

        val multiplier = context.snapshot.powerSaveMultiplier
        val effect = multiplier?.let {
            val change = ((1 - it) * 100).roundToInt()
            if (change > 0) " On this phone it has reduced drain by roughly $change%." else ""
        }.orEmpty()

        return listOf(
            if (latest.powerSaveEnabled) {
                ForecastDriver(
                    headline = "Power saving turned on",
                    detail = "The forecast now uses this phone's power-saving behaviour.$effect",
                    direction = DriverDirection.BETTER,
                    magnitude = multiplier,
                )
            } else {
                ForecastDriver(
                    headline = "Power saving turned off",
                    detail = "The forecast has switched back to normal-mode drain rates.$effect",
                    direction = DriverDirection.WORSE,
                    magnitude = multiplier,
                )
            },
        )
    }

    private fun screenTimeComparison(context: ForecastContext): List<ForecastDriver> {
        val latest = context.latest
        val recentScreenMs = latest.recentScreenTimeMs ?: return emptyList()

        val historical = context.cleaned.observations
            .dropLast(1)
            .mapNotNull { it.recentScreenTimeMs }
            .takeIf { it.size >= 8 }
            ?: return emptyList()

        val typical = RobustStats.median(historical.map { it.toDouble() }) ?: return emptyList()
        if (typical <= 0.0) return emptyList()

        val ratio = recentScreenMs / typical
        if (ratio in (1 - SCREEN_TIME_TOLERANCE)..(1 + SCREEN_TIME_TOLERANCE)) return emptyList()

        val recentMinutes = (recentScreenMs / 60_000.0).roundToInt()
        val typicalMinutes = (typical / 60_000.0).roundToInt()

        return listOf(
            if (ratio > 1) {
                ForecastDriver(
                    headline = "More screen time than usual in the last hour",
                    detail = "About $recentMinutes minutes of screen-on time, against $typicalMinutes " +
                        "minutes typical for this phone.",
                    direction = DriverDirection.WORSE,
                    magnitude = ratio,
                )
            } else {
                ForecastDriver(
                    headline = "Less screen time than usual in the last hour",
                    detail = "About $recentMinutes minutes of screen-on time, against $typicalMinutes " +
                        "minutes typical for this phone.",
                    direction = DriverDirection.BETTER,
                    magnitude = ratio,
                )
            },
        )
    }

    /**
     * Notes a coincidence between a kind of foreground activity and elevated drain.
     *
     * The wording is deliberate. Android gives aggregate foreground time by app category, and
     * that supports "these coincided" — it does not support "this app consumed 12.4 % of your
     * battery", so that claim is never made.
     */
    private fun usageCoincidence(context: ForecastContext): List<ForecastDriver> {
        val category = context.latest.dominantUsageCategory ?: return emptyList()
        val foregroundMs = context.latest.recentForegroundUsageMs ?: return emptyList()
        if (foregroundMs < MIN_FOREGROUND_MS) return emptyList()

        val recent = context.estimates.blendedPercentPerHour ?: return emptyList()
        val baseline = context.snapshot.globalDrain?.mean ?: return emptyList()
        if (baseline <= MIN_BASELINE || recent.ratePerHour <= baseline * USAGE_COINCIDENCE_RATIO) {
            return emptyList()
        }

        val description = when (category) {
            com.batterycast.quant.telemetry.model.UsageCategory.VIDEO -> "extended video-app activity"
            com.batterycast.quant.telemetry.model.UsageCategory.GAME -> "extended game activity"
            com.batterycast.quant.telemetry.model.UsageCategory.MAPS_NAVIGATION -> "extended maps activity"
            com.batterycast.quant.telemetry.model.UsageCategory.SOCIAL -> "extended social-app activity"
            com.batterycast.quant.telemetry.model.UsageCategory.COMMUNICATION -> "extended calling or messaging activity"
            else -> return emptyList()
        }

        return listOf(
            ForecastDriver(
                headline = "Higher drain alongside $description",
                detail = "High screen usage and $description coincided with increased battery drain. " +
                    "BatteryCast cannot measure how much any single app used, so this is a " +
                    "coincidence in time, not an attribution.",
                direction = DriverDirection.WORSE,
                magnitude = null,
            ),
        )
    }

    /** Says plainly when the forecast is less certain than usual, and why. */
    private fun uncertaintyNotes(context: ForecastContext): List<ForecastDriver> {
        val notes = mutableListOf<ForecastDriver>()
        val capabilities = context.capabilities

        if (capabilities.chargeCounter == FieldSupport.UNSUPPORTED &&
            capabilities.currentNow == FieldSupport.UNSUPPORTED
        ) {
            notes += ForecastDriver(
                headline = "This device reports battery percentage only",
                detail = "Charge-counter and current readings are unavailable here, so drain is " +
                    "estimated from percentage changes. That is coarser, and the forecast interval " +
                    "reflects it.",
                direction = DriverDirection.UNCERTAINTY,
                magnitude = null,
            )
        }

        if (context.thermalBucket == ThermalBucket.HOT) {
            notes += ForecastDriver(
                headline = "The device is running hot",
                detail = "Thermal throttling changes both drain and charging speed, so the " +
                    "prediction interval is wider than usual.",
                direction = DriverDirection.UNCERTAINTY,
                magnitude = null,
            )
        }

        if (context.maturity <= DataMaturity.PRELIMINARY) {
            notes += ForecastDriver(
                headline = "Still building a picture of this phone",
                detail = "This is a preliminary estimate from live measurements. It will get " +
                    "noticeably sharper once a few hours of real discharge have been observed.",
                direction = DriverDirection.UNCERTAINTY,
                magnitude = null,
            )
        }

        val residuals = context.snapshot.residualModel
        if (residuals.hasEmpiricalSupport && residuals.volatility > residuals.scale * VOLATILITY_ALERT_RATIO) {
            notes += ForecastDriver(
                headline = "Recent behaviour has been less predictable",
                detail = "Forecast errors over the last few days have been larger than this phone's " +
                    "long-run pattern, so the interval has widened to match.",
                direction = DriverDirection.UNCERTAINTY,
                magnitude = residuals.volatility,
            )
        }

        return notes
    }

    private fun format(value: Double): String = String.format("%.1f", value)

    private companion object {
        const val MIN_BASELINE = 0.2
        const val MIN_REPORTABLE_DIFFERENCE = 15
        const val RECENT_WINDOW_MS = 90 * 60 * 1000L
        const val MIN_TEMPERATURE_DELTA_C = 2.5
        const val POWER_SAVE_WINDOW_MS = 3 * 60 * 60 * 1000L
        const val SCREEN_TIME_TOLERANCE = 0.4
        const val MIN_FOREGROUND_MS = 10 * 60 * 1000L
        const val USAGE_COINCIDENCE_RATIO = 1.25
        const val VOLATILITY_ALERT_RATIO = 1.5
    }
}
